version: "3.1"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - db
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: glamhoth
      MYSQL_PASSWORD: docker
  java:
    build: ./java-container
    image: glamhoth/java:8
    container_name: java
    restart: always
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: glamhoth
      database__connection__password: docker
      database__connection__database: db
    depends_on:
      - mysql
    networks:
      - db
    ports:
      - "8081:8080"
    # entrypoint: ["wait.sh", "mysql", "--", "dupa.sh"]
    # command: ["java", "-cp", ".:mysql-connector-java-8.0.13.jar", "Main"]
    # command: ["echo", "dupsko"]

volumes:
  mysql-volume:

networks:
  db:

