version: "3.1"

services:
  mysql:
    image: mysql
    container_name: pwcho2018-83722
    networks:
      bridge_zadanie_1:
        ipv4_address: 10.0.10.3
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: mbl
      MYSQL_PASSWORD: root
      
  java:
    image: michalblaszczykpollub/lab6apache
    container_name: java
    restart: always
    depends_on:
      - mysql
    networks:
      bridge_zadanie_1:
        ipv4_address: 10.0.10.4
    ports:
      - "8081:8080"

networks:
  bridge_zadanie_1:
    driver: bridge

